### ISSUE TITLE
フィルタリング処理で生成されるresults.filtering.jsonlとresult.filtering.jsonlのテキストエンコーディングが違う

### ISSUE THREAD

**Issue by uchidama** [matsuolab/ucllm_nedo_prod#2]
仕様なのかどうか判断が迷うのですが、あげさせてもらいます。

次のようにwikipediaのフィルタリング処理のコマンドを実行します。
`python -m preprocessing.download_dataset --dataset=wikipedia --split=20240301
`
フィルタリング通過データの全てがresults.filtering.jsonlに。
各サブフォルダのフィルタリング通過データがサブフォルダ名/result.filtering.jsonlに。
保存されます。

READMEに従ってDedup処理を行うと、results.filtering.jsonlを使うとjsonの読み込み失敗で全てエラーに。
result.filtering.jsonlはDedup処理が正常に行える。
という現象が起きました。

lessコマンドでresults.filtering.jsonlに書かれた情報を見てみると、
`"{\"text\": \"{{Otheruses||日本の漫画家|後藤寿
`
と、\が入っています。

0/result.filtering.jsonlに書かれた情報を見てみると、
`{"text": "'''永田トマト'''(ながたトマト
`
と、\が入っていません。

`ucllm_nedo_prod/preprocessing/preprocessing/filtering/__main__.py
`
を見てみると、results.filtering.jsonlの書き込み時にutf-8エンコーディングの指定があり、これが影響しているのではないかと思われますが、意図した仕様なのかが判断できませんでした。

個人的にはresults.filtering.jsonlが、そのデータセットのフィルタリング結果。という扱いでdedupにかけるという流れのほうが良いのかなと思うのですが、いかがでしょうか？

**Comment by YU-ZHENXUAN-ucllm** [comment]
ご指摘ありがとうございます。最新バージョンv0.4でfilteringのコードを修正済みです。
原因は文字列のjsonをjson.dumpで再度jsonにしていたため、二重に文字列化されていた。

https://github.com/matsuolab/ucllm_nedo_prod/blob/main/data_management/preprocessing/filtering/__main__.py#L70

**Comment by uchidama** [comment]
了解しました。
ご対応ありがとうございます！
