### ISSUE TITLE
README.mdの画像リンク切れ

### ISSUE THREAD

**Issue by masachika-kamada** [matsuolab/ucllm_nedo_prod#3]
`data_management` ディレクトリの `README.md` の冒頭の `スクリーンショット 2024-02-27 14 21 58` がリンク切れになっていました

画像の追加または論文内での画像番号への修正をしていただけますと幸いです

**Comment by kenoharada** [comment]
@masachika-kamada 
ありがとうございます
取り急ぎの共有ですが該当の図は
論文
A Survey of Large Language Models, https://arxiv.org/pdf/2303.18223.pdf
の
Fig. 7: An illustration of a typical data preprocessing pipeline for pre-training large language models.
となります
